### ISSUE TITLE
calling grift hello causes sql: Register called twice for driver postgres

### ISSUE THREAD

**Issue by u007** [markbates/grift#20]
hi

i tried run in coke new project, and it works.
but for my project, none task works
```
$ grift hello
panic: sql: Register called twice for driver postgres

goroutine 1 [running]:
database/sql.Register(0x4cae8a4, 0x8, 0x5360080, 0x53e6700)
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:50 +0x1ad
project/vendor/github.com/lib/pq.init.0()
	/Users/james/www/gowork/src/project/vendor/github.com/lib/pq/conn.go:49 +0x60
project/vendor/github.com/lib/pq.init()
	<autogenerated>:1 +0x782
project/vendor/github.com/markbates/pop.init()
	<autogenerated>:1 +0x8c
project/db.init()
	<autogenerated>:1 +0x49
project/grifts.init()
	<autogenerated>:1 +0x82
main.init()
	<autogenerated>:1 +0x44

```

**Comment by u007** [comment]
i did a glide up and it seems to fix this issue
